//GET http://localhost:8080/devops_starter_war_exploded/api/xxx

//###
//POST http://localhost:8080/devops_starter_war_exploded/api/xxx
//Content-Type: application/json
//#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

//{"str1": "First Property", "str2": "Second Property"}

GET http://localhost:8080/recap/api/info

###
POST http://localhost:8080/recap/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "test123"
}
###
GET http://localhost:8080/recap/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2ODE3MzY5NjQsImlhdCI6MTY4MTczNTE2NCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.9AZ_MNqrJEG6Xh-kwi3TjNIHjD3Pi6c6PbsxKcGBEdM